In [129]:
import  pandas as pd

In [130]:
df = pd.read_csv("./titanic/train.csv")

In [131]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [132]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [133]:
df.shape

(891, 12)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [135]:
summary= pd.DataFrame({"columns":df.columns,"dtype":df.dtypes.values,"missing":df.isnull().sum().values,"unique": df.nunique().values}) 
summary=summary.sort_values("missing",ascending=False)

In [136]:
summary

        columns    dtype  missing  unique
10        Cabin   object      687     147
5           Age  float64      177      88
11     Embarked   object        2       3
0   PassengerId    int64        0     891
3          Name   object        0     891
2        Pclass    int64        0       3
1      Survived    int64        0       2
4           Sex   object        0       2
7         Parch    int64        0       7
6         SibSp    int64        0       7
9          Fare  float64        0     248
8        Ticket   object        0     681

In [137]:
# Value counts & proportions
# For Pclass, Gender, and Embarked, show value counts and percentages (as a DataFrame).
cols=["Pclass","Sex","Embarked"]

for col in cols:
    values=df[col].value_counts(dropna=False)
    proportions=df[col].value_counts(normalize=True,dropna=False)*100

    result=pd.DataFrame({"values":values,"proportions":proportions.round(2)})
    print(result)

        values  proportions
Pclass
3          491        55.11
1          216        24.24
2          184        20.65
        values  proportions
Sex
male       577        64.76
female     314        35.24
          values  proportions
Embarked
S            644        72.28
C            168        18.86
Q             77         8.64
NaN            2         0.22

In [138]:
female_firstclass_over_30=df[(df["Sex"]=="female")&(df["Pclass"]==1)&(df["Age"]>30)]
female_firstclass_over_30=female_firstclass_over_30.sort_values("Fare",ascending=False)

In [139]:
female_firstclass_over_30.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C
716,717,1,1,"Endres, Miss. Caroline Louise",female,38.0,0,0,PC 17757,227.5250,C45,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.0,0,0,PC 17757,227.5250,NaN,C
779,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton Mc...",female,43.0,0,1,24160,211.3375,B3,S
318,319,1,1,"Wick, Miss. Mary Natalie",female,31.0,0,2,36928,164.8667,C7,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
609,610,1,1,"Shutes, Miss. Elizabeth W",female,40.0,0,0,PC 17582,153.4625,C125,S
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C

In [140]:
print(df["Age"].mean().round(2))
print(df["Age"].median())
print(df["Age"].mode()[0])

29.7
28.0
24.0

In [141]:
df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [142]:
print("\nOverall survival rate:")
print(df["Survived"].mean().round(2))

Overall survival rate:
0.38

In [143]:
print("Survival rate by Gender:")
print(df.groupby("Sex")["Survived"].mean().round(2))

Survival rate by Gender:
Sex
female    0.74
male      0.19
Name: Survived, dtype: float64

In [144]:
print("Before filling missing:",df["Age"].isnull().sum())
df["Age_imputed"] = df.groupby(["Pclass", "Sex"])["Age"].transform(
    lambda x: x.fillna(x.median())
)
print("After filling missing:",df["Age_imputed"].isnull().sum())

Before filling missing: 177
After filling missing: 0

In [145]:
for group_keys, group_df in df.groupby(["Pclass", "Sex"]):
    print("Group:", group_keys)
    print(group_df.head(3))  # show first 3 rows from this group
    print("-" * 50)

Group: (np.int64(1), 'female')
    PassengerId  Survived  Pclass  \
1             2         1       1
3             4         1       1
11           12         1       1

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
11                           Bonnell, Miss. Elizabeth  female  58.0      0

    Parch    Ticket     Fare Cabin Embarked  Age_imputed
1       0  PC 17599  71.2833   C85        C         38.0
3       0    113803  53.1000  C123        S         35.0
11      0    113783  26.5500  C103        S         58.0
--------------------------------------------------
Group: (np.int64(1), 'male')
    PassengerId  Survived  Pclass                            Name   Sex   Age  \
6             7         0       1         McCarthy, Mr. Timothy J  male  54.0
23           24         1       1    Sloper, Mr. William Thompson  male  28.0
27           28         0       1  Fortune, Mr. Charles Alexander  male  19.0

    SibSp  Parch  Ticket      Fare        Cabin Embarked  Age_imputed
6       0      0   17463   51.8625          E46        S         54.0
23      0      0  113788   35.5000           A6        S         28.0
27      3      2   19950  263.0000  C23 C25 C27        S         19.0
--------------------------------------------------
Group: (np.int64(2), 'female')
    PassengerId  Survived  Pclass  \
9            10         1       2
15           16         1       2
41           42         0       2

                                                 Name     Sex   Age  SibSp  \
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
41  Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.0      1

    Parch  Ticket     Fare Cabin Embarked  Age_imputed
9       0  237736  30.0708   NaN        C         14.0
15      0  248706  16.0000   NaN        S         55.0
41      0   11668  21.0000   NaN        S         27.0
--------------------------------------------------
Group: (np.int64(2), 'male')
    PassengerId  Survived  Pclass                          Name   Sex   Age  \
17           18         1       2  Williams, Mr. Charles Eugene  male   NaN
20           21         0       2          Fynney, Mr. Joseph J  male  35.0
21           22         1       2         Beesley, Mr. Lawrence  male  34.0

    SibSp  Parch  Ticket  Fare Cabin Embarked  Age_imputed
17      0      0  244373  13.0   NaN        S         30.0
20      0      0  239865  26.0   NaN        S         35.0
21      0      0  248698  13.0   D56        S         34.0
--------------------------------------------------
Group: (np.int64(3), 'female')
    PassengerId  Survived  Pclass  \
2             3         1       3
8             9         1       3
10           11         1       3

                                                 Name     Sex   Age  SibSp  \
2                              Heikkinen, Miss. Laina  female  26.0      0
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1

    Parch            Ticket     Fare Cabin Embarked  Age_imputed
2       0  STON/O2. 3101282   7.9250   NaN        S         26.0
8       2            347742  11.1333   NaN        S         27.0
10      1           PP 9549  16.7000    G6        S          4.0
--------------------------------------------------
Group: (np.int64(3), 'male')
   PassengerId  Survived  Pclass                      Name   Sex   Age  SibSp  \
0            1         0       3   Braund, Mr. Owen Harris  male  22.0      1
4            5         0       3  Allen, Mr. William Henry  male  35.0      0
5            6         0       3          Moran, Mr. James  male   NaN      0

   Parch     Ticket    Fare Cabin Embarked  Age_imputed
0      0  A/5 21171  7.2500   NaN        S         22.0
4      0     373450  8.0500   NaN        S         35.0
5      0     330877  8.4583   NaN        Q         25.0
--------------------------------------------------

In [146]:
df["Title"] = df["Name"].str.extract(r",\s*([^\.]+)\.")

print("\nTitle counts:")
print(df["Title"].value_counts())

Title counts:
Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [148]:
df["family_size"]=df["SibSp"]+df["Parch"]+1
df["isAlone"]=df["family_size"]==1
print("Alone survived:", df.groupby("isAlone")["Survived"].mean())

Alone survived: isAlone
False    0.505650
True     0.303538
Name: Survived, dtype: float64

In [150]:
pivot = df.pivot_table(index="Pclass",columns="Sex",values="Survived",aggfunc="mean")
print(pivot)

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [151]:
grouped = df.groupby(["Pclass", "Embarked"])[["Fare", "Age_imputed"]].mean()

print("\nGroupby - Avg Fare & Age_imputed by Pclass & Embarked:")
print(grouped)

Groupby - Avg Fare & Age_imputed by Pclass & Embarked:
                       Fare  Age_imputed
Pclass Embarked
1      C         104.718529    37.988235
       Q          90.000000    38.500000
       S          70.364862    38.271024
2      C          25.358335    23.617647
       Q          12.350000    38.333333
       S          20.327439    30.355671
3      C          11.214083    21.983636
       Q          11.183393    24.194444
       S          14.644083    25.453258

In [154]:
df["Cabin"]=df["Cabin"].fillna("Unknown")
df["CabinDeck"]=df["Cabin"].str[0]
print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare    Cabin Embarked  Age_imputed Title  \
0      0         A/5 21171   7.2500  Unknown        S         22.0    Mr
1      0          PC 17599  71.2833      C85        C         38.0   Mrs
2      0  STON/O2. 3101282   7.9250  Unknown        S         26.0  Miss
3      0            113803  53.1000     C123        S         35.0   Mrs
4      0            373450   8.0500  Unknown        S         35.0    Mr

   family_size  isAlone CabinDeck
0            2    False         U
1            2    False         C
2            1     True         U
3            2    False         C
4            1     True         U